#!/bin/bash

# Clear the terminal window
clear

# Output ASCII art header
function header {
	echo "___  ___          _ _     _ _         "
	echo "|  \/  |         | | |   (_) |        "
	echo "| .  . | __ _  __| | |    _| |__  ___ "
	echo "| |\/| |/ _\` |/ _\` | |   | | '_ \/ __|"
	echo "| |  | | (_| | (_| | |___| | |_) \__ \\"
	echo "\_|  |_/\__,_|\__,_\_____/_|_.__/|___/"
	echo "                                      "
}

# Outputs usage instructions
function usage {
	echo "usage: $0 [file] [args]"
	echo "	file	filename for the story (minus the extension)"
	echo "	args	madlib substitutions"
	echo -e "\r"
	exit 1
}

header

[[ $# -eq 0 ]] && usage

p_basic="\[Noun]|\[Verb]|\[Pronoun]|\[Adjective]|\[Adverb]"
p_proper="\[Proper_Noun]"
p_plural="\[Plural_Noun]"
p_misc="\[Place]|\[Number]|\[Body_Part]|\[Exclamation]"

pattern="$p_basic|$p_proper|$p_plural|$p_misc"
story="./stories/"$1".txt"

# ESC_SEQ="\x1b["
# COL_RESET=$ESC_SEQ"39;49;00m"
# COL_RED=$ESC_SEQ"31;01m"

count=1
while read line; do
	output=()

	for word in $line; do
		# Check if word contains the desired regex pattern
		if [[ $word =~ $pattern ]]
			then
				count=$[$count + 1]
				eval lib=\${$count}
		fi

		# If $lib is not undefined
		if [[ ! -z $lib ]]
			then
				output+=$(printf "%s " $word | sed -E 's/'$pattern'/'$lib'/')
			else
				output+=$(printf "%s " $word)
		fi
	done

	echo $output
done < $story

echo -e "\r"