#!/bin/bash

# Clear the terminal window
clear

# Output ASCII art header
function header {
	echo "___  ___          _ _     _ _         "
	echo "|  \/  |         | | |   (_) |        "
	echo "| .  . | __ _  __| | |    _| |__  ___ "
	echo "| |\/| |/ _\` |/ _\` | |   | | '_ \/ __|"
	echo "| |  | | (_| | (_| | |___| | |_) \__ \\"
	echo "\_|  |_/\__,_|\__,_\_____/_|_.__/|___/"
	echo "                                      "
}

header

#echo "the $1 fox $2 over the $3 dog."

pattern="\[Adjective]"

count=0
while read line; do
	# Check if line contains the desired regex pattern
	if [[ $line =~ $pattern ]]
		then
			count=$[$count + 1]
			eval lib=\${$count}
	fi
	echo $line | sed 's/'$pattern'/'$lib'/'
done < "./stories/test.txt"